apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcps-backend.fullname" . }}
  labels:
    {{- include "mcps-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  ENCRYPTION_KEY: {{ .Values.secrets.ENCRYPTION_KEY | quote }}
  API_KEY: {{ .Values.secrets.API_KEY | quote }}
  BAN_LIST: {{ .Values.secrets.BAN_LIST | quote }}
  CLOUDFLARE_TUNNEL_TOKEN: {{ .Values.cloudflared.tunnelToken | quote }}
